# Cloudly Plugin Configuration
# Version: 1.0.0.0 (Epoch.Major.Minor.Patch)

# Plugin Settings
plugin:
  # Language for messages (future feature)
  language: "en"

# Feature toggles (add features here as you develop them)
features:
  # Example feature toggle
  # example-feature: true
  
# Database configuration (if needed in the future)
# database:
#   type: "sqlite" # sqlite, mysql, postgresql
#   host: "localhost"
#   port: 3306
#   database: "cloudly"
#   username: "root"
#   password: "password"
#   
#   # Connection pool settings
#   pool:
#     minimum-connections: 2
#     maximum-connections: 10
#     connection-timeout: 30000

# Message configuration
messages:
  # Prefix for all plugin messages
  prefix: "&8[&bCloudly&8]&r "
  
  # Common messages
  no-permission: "&cYou don't have permission to use this command."
  player-only: "&cThis command can only be used by players."
  reload-success: "&aCloudly has been reloaded successfully!"
  reload-failed: "&cFailed to reload Cloudly. Check console for errors."

# Development settings (remove in production)
development:
  # Enable development mode features
  enabled: true
  
  # Show additional debug information
  verbose-logging: false
