# Cloudly Plugin Configuration
# Version: 1.0.0.0

plugin:
  # Language setting for the plugin
  # Available languages: en (English), de (German), fr (French), es (Spanish), pt (Portuguese), pl (Polish), ru (Russian), zh (Chinese)
  language: "en"

features:
  # Example feature toggle
  # example-feature: true
  

# Whitelist System Configuration
whitelist:
  # Enable/disable the custom whitelist system (overrides vanilla whitelist)
  enabled: false
  
  # Cache settings for performance optimization
  cache:
    # How long to cache whitelist data (in minutes)
    duration: 30
    # Maximum number of entries to cache
    max-size: 1000
  
  # Kick message for non-whitelisted players (supports color codes)
  kick-message: "&cYou are not whitelisted on this server!"

database:
  type: "sqlite"

  sqlite:
    file: "cloudly.db"

  mysql:  
    host: "localhost"
    port: 3306
    database: "cloudly"
    username: "username"
    password: "password"