# Cloudly Plugin Configuration
# Version: 1.0.0.0

plugin:
  # Language setting for the plugin
  # Available languages: en (English), de (German), fr (French), es (Spanish), pt (Portuguese), pl (Polish), ru (Russian), zh (Chinese)
  language: "en"

features:
  # Example feature toggle
  # example-feature: true
  

database:
  type: "sqlite"

  sqlite:
    file: "cloudly.db"

  mysql:  
    host: "localhost"
    port: 3306
    database: "cloudly"
    username: "username"
    password: "password"