# Cloudly Plugin Configuration
# Version: 1.0.0.0

plugin:
  language: "en"

features:
  # Example feature toggle
  # example-feature: true
  

database:
  type: "sqlite"

  sqlite:
    file: "cloudly.db"

  mysql:  
    host: "localhost"
    port: 3306
    database: "cloudly"
    username: "username"
    password: "password"