# ☁️ Cloudly Plugin Configuration ☁️

# Plugin Settings
plugin:
  # Enable debug mode for verbose logging
  debug: false
  
  # Available languages: en (English), de (German)
  language: "en"

# Release Radar Settings
release-radar:
  # Enable release radar functionality - Messages will be sent to the console when a new release or pre-release is available.
  enabled: true
  
  # Release channel: "release" for stable releases only, "pre-release" for all releases including pre-releases
  channel: "release"