# Cloudly Plugin Configuration
# This file defines the plugin metadata for PaperMC/Bukkit

name: ${name}
version: ${version}
main: ${main}
api-version: 1.18
author: Gerrxt07
description: High-performance Minecraft Server Management plugin built with Kotlin
website: https://github.com/gerrxt07/cloudly

# Minimum Minecraft version support
# 1.18+ for Paper API compatibility
folia-supported: true

# Plugin loading
load: STARTUP
depend: []
softdepend: []
loadbefore: []

# Commands section (add commands here when needed)
commands:
  cloudly:
    description: Main Cloudly command
    usage: /cloudly [info|reload]
    permission: cloudly.command
    permission-message: You don't have permission to use this command.
  
  whitelist:
    description: Cloudly whitelist management
    usage: /whitelist <add|remove|enable|disable|list|reload|apply|admin> [player] [page]
    permission: cloudly.whitelist
    permission-message: You don't have permission to use whitelist commands.

# Permissions section (add permissions here when needed)
permissions:
  cloudly.admin:
    description: Access to all Cloudly admin commands
    default: op
  cloudly.command:
    description: Basic access to Cloudly commands
    default: true
  cloudly.command.info:
    description: Access to view plugin information
    default: true
  
  # Whitelist permissions
  cloudly.whitelist:
    description: Basic whitelist command access
    default: op
    children:
      cloudly.whitelist.list: true
  
  cloudly.whitelist.*:
    description: All whitelist permissions
    default: op
    children:
      cloudly.whitelist.add: true
      cloudly.whitelist.remove: true
      cloudly.whitelist.toggle: true
      cloudly.whitelist.list: true
      cloudly.whitelist.reload: true
      cloudly.whitelist.admin: true
  
  cloudly.whitelist.add:
    description: Permission to add players to whitelist
    default: op
  
  cloudly.whitelist.remove:
    description: Permission to remove players from whitelist
    default: op
  
  cloudly.whitelist.toggle:
    description: Permission to enable/disable whitelist
    default: op
  
  cloudly.whitelist.list:
    description: Permission to view whitelisted players
    default: op
  
  cloudly.whitelist.reload:
    description: Permission to reload whitelist data
    default: op
  
  # Application system permissions
  cloudly.whitelist.apply:
    description: Permission to submit whitelist applications
    default: true
  
  cloudly.whitelist.admin:
    description: Access to whitelist admin commands
    default: op
    children:
      cloudly.whitelist.admin.review: true
      cloudly.whitelist.admin.approve: true
      cloudly.whitelist.admin.deny: true
  
  cloudly.whitelist.admin.review:
    description: Permission to review whitelist applications
    default: op
  
  cloudly.whitelist.admin.approve:
    description: Permission to approve whitelist applications
    default: op
  
  cloudly.whitelist.admin.deny:
    description: Permission to deny whitelist applications
    default: op