name: Cloudly
version: ${version}
main: de.cloudly.CloudlyPaper
author: Phantom
description: A simple plugin to manage a server. Useable with both Velocity and Paper servers.
api-version: 1.20
load: STARTUP

permissions:
  cloudly.admin:
    description: Allows the player to manage the server.
    default: op
